### ISSUE TITLE
Adding design template

### ISSUE THREAD

**Issue by nrooney024** [nrooney024/monday-motivation#3]
Let's add a template from HTML5up to spruce it up a little!

**Comment by nrooney024** [comment]
Potential template https://html5up.net/highlights

**Comment by DavidCao4626** [comment]
Potential template as well! https://templatemo.com/templates/templatemo_517_timeless/

**Comment by DavidCao4626** [comment]
Potential template as well! https://templatemo.com/templates/templatemo_517_timeless/
